### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by gad2103** [benkeen/ace-diff#4]
please add bower support!

**Comment by benkeen** [comment]
Ah... I see you've already added your repo as ace-diff. k.

**Comment by gad2103** [comment]
Yes. I also made an angular directive for it. I'm thinking about putting
that out there too

**Comment by benkeen** [comment]
Nice!

**Comment by gad2103** [comment]
just to let you know, we're using this in an important application at the
nytimes :)

**Comment by benkeen** [comment]
Very cool, good to hear about! Thanks @gad2103!
