### ISSUE TITLE
diffs not lining up

### ISSUE THREAD

**Issue by tinba12** [benkeen/ace-diff#8]
It finds the diffs correctly but the gutter does not display properly and the highlighting are off.  I believe it is caused by the line height.

![blue_steel_cpm_and_blue_steel_cpm_and_datepicker_widget___jquery_ui_api_documentation](https://cloud.githubusercontent.com/assets/13382144/9312043/f4785a00-44df-11e5-8afe-735082d27468.png)

**Comment by benkeen** [comment]
Whoah! Yes possibly so. You may actually need to resolve that yourself by adding some CSS to override the line height for your environment. The default CSS defines the right height but it's probably being overridden by something on your end.

**Comment by tinba12** [comment]
Have you tried this with the latest version of ACE?  I am pretty sure line 87, assigning the line height, does not work. It returns zero which cause all of the diffs to be at the top.

**Comment by benkeen** [comment]
Ah, good to know! I'll try to take a look tonight.

**Comment by benkeen** [comment]
[bump for me...]

**Comment by benkeen** [comment]
Hey @tinba12, I updated ace to the latest version but everything still looks okay to me. If you still have the page handy that illustrates the problem, mind posting it here?

**Comment by tinba12** [comment]
It looks like the updated version fixed the issue.

![blue_steel_cpm_and_transfers](https://cloud.githubusercontent.com/assets/13382144/11658920/22a6f4e6-9d8b-11e5-852f-9507b3ab44f5.png)

**Comment by benkeen** [comment]
Great, thanks for the heads up!

**Comment by tinba12** [comment]
It looks like that what was happening is that when the divs for the editors are display:none; the line height is screwed up. When I the divs are shown the line heights are correct.
